### ISSUE TITLE
add meta tags

### ISSUE THREAD

**Issue by devopstoday11** [intelops/external-docs#32]
when I checked https://www.opengraph.xyz/ , our docs site doesn't have any meta tags and preview images.  
Please add meta tags for LinkedIn, FB, Twitter, Discord, Slack, Youtube, etc. 
And also, explain where and how I can add more new meta tags in future myself. 
@tfsojon

**Comment by tfsojon** [comment]
@devopstoday11 updated please check

**Comment by devopstoday11** [comment]
@tfsojon ,
Thank you. 
Quick question, opengraph is opensource and we are not going to get any license issues in future right?
