### ISSUE TITLE
adding Google Tag Manager (GTM) to the site 

### ISSUE THREAD

**Issue by devopstoday11** [intelops/external-docs#37]
GTM is a tag management tool for tracking website traffic data for analytics and attribution. 
Google Tag Manager (GTM) is a tag management tool wherein we can integrate GA4 and other third-party tools (email marketing tool, linkedin ads, google ads, CMS ecommerce) to set up tracking. Instead of adding all the codes individually, we only need to add GTM code on the website - https://marketingplatform.google.com/about/tag-manager/

https://vilcins.medium.com/how-to-add-google-tag-manager-code-to-your-hugo-website-e0b1c8990f26 -- reference blog.

@tfsojon If I provide our GTM code, could you add it to website and docs sites and test it to ensure it's working fine?

**Comment by devopstoday11** [comment]
> @tfsojon use same GTM code for docs site too. I confirmed with marketing team.
> 
> This is what was used for main website - [intelops/website#201 (comment)](https://github.com/intelops/website/issues/201#issuecomment-1627528964)

@tfsojon

**Comment by tfsojon** [comment]
@devopstoday11 Done
