### ISSUE TITLE
after doing GTM code merge into chandu and also into main branch some things in the footer got disappeared. 

### ISSUE THREAD

**Issue by devopstoday11** [intelops/external-docs#43]
![image](https://github.com/intelops/external-docs/assets/59978378/9491ebeb-b950-406a-a78c-3eb466f45ac0)

See on the left side in the footer, those are no more in the latest site after the GTM code was merged. I didn't notice and merged everything into main branch. Please fix this. 
@tfsojon

**Comment by devopstoday11** [comment]
https://github.com/intelops/external-docs/pull/40#issuecomment-1645023652 
@tfsojon

**Comment by tfsojon** [comment]
@devopstoday11 issue fixed now.
