### ISSUE TITLE
issue with internal docs site with same exact template

### ISSUE THREAD

**Issue by devopstoday11** [intelops/external-docs#8]
https://www.loom.com/share/603fc0afa4244b728e4ac4ec0713a49a

**Comment by tfsojon** [comment]
Basically in some cases Hugo does not works as we want.
Like in our doc site it has unlimited inner-level of sections. also we have to manage the search functionality for multiple versions in a single site. where Hugo don't generates multiple JSON file.

So we use Hugo's different type of features to achieve this. In some cases I use JavaScript to get the URL index.

the doc will perfectly works with this type of baseURL's.

https://something.com/ `[supports multilingual and version search]`
https://something.something.com/ `[supports multilingual and version search]`

If you want to keep that url then we have to re-work on this for your internal-doc but we can't make support for every-type of baseURL's.

Hope you understand.

**Comment by devopstoday11** [comment]
@tfsojon, yeah got it. Thanks for explaining. What should I change for my internal docs site to make the URL work fine?

**Comment by tfsojon** [comment]
If you want to keep the URL like this `https://tariandev_intelops.gitlab.io/documentation/internal-docs-hugosite`
then you have to change the split index.

### search for `split` and open this pages
![image](https://user-images.githubusercontent.com/87603786/199390997-93ac15ce-623e-49fd-a2bc-bdf1d4d3f3fd.png)

### open `menu.html`
![image](https://user-images.githubusercontent.com/87603786/199391808-250cb812-cfc6-4a9f-866d-55907e03ee06.png)

### open `default.html` and update this
![image](https://user-images.githubusercontent.com/87603786/199392029-0e171298-fb7f-47f0-bf29-6e34f492908d.png)
